version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongod.conf:/etc/mongod.conf  # Mount custom config file
    command: mongod --config /etc/mongod.conf  # Use custom config file

  server:
    build: ./backend
    ports:
      - "2026:2026"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/dc # No authentication

  client:
    build: ./frontend
    ports:
      - "2025:2025"
    depends_on:
      - server

volumes:
  mongo-data:
    driver: local