services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "10.0.1.221:27017:27017"  # Bind MongoDB to host IP and port
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data
      - ./mongod.conf:/etc/mongod.conf  # Mount custom config file
    command: mongod --config /etc/mongod.conf
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: ./backend
    restart: unless-stopped
    ports:
      - "10.0.1.221:2026:2026"  # Bind backend to host IP and port
    depends_on:
      mongo:
        condition: service_healthy  # Wait for MongoDB to be ready
    environment:
      - MONGO_URI=mongodb://mongo:27017/mernapp  # MongoDB connection string

  client:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "10.0.1.221:2025:80"  # Map container's Nginx (port 80) to host port 2025
    depends_on:
      - server  # Ensure frontend starts after the backend
    volumes:
     # Serve React build files
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  mongo-data:
    driver: local
