
services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongod.conf:/etc/mongod.conf  # Mount custom config file
    command: mongod --config /etc/mongod.conf  # Use custom config file
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: ./backend
    ports:
      - "2026:2026"
    depends_on:
      mongo:
        condition: service_healthy  # Wait for MongoDB to be ready
    environment:
      - MONGO_URI=mongodb://mongo:27017/mernapp  # No authentication

  client:
    build: ./frontend
    ports:
      - "2025:2025"
    depends_on:
      - server

volumes:
  mongo-data:
    driver: local
