version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./backend
    ports:
      - "2026:2026"  
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mernapp

  client:
    build: ./frontend
    ports:
      - "2025:2025"  
    depends_on:
      - server

volumes:
  mongo-data: