
services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "10.0.1.221:27017:27017"  # Bind MongoDB to host IP 10.0.1.221 and port 27017
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data
      - ./mongod.conf:/etc/mongod.conf  # Mount custom config file
    command: mongod --config /etc/mongod.conf  # Use custom config file
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: ./backend
    ports:
      - "10.0.1.221:2026:2026"  # Bind backend to host IP 10.0.1.221 and port 2026
    depends_on:
      mongo:
        condition: service_healthy  # Wait for MongoDB to be ready
    environment:
      - MONGO_URI=mongodb://mongo:27017/mernapp  # MongoDB connection string

  client:
    build: ./frontend
    ports:
      - "10.0.1.221:2025:2025"  # Bind frontend to host IP 10.0.1.221 and port 2025


volumes:
  mongo-data:
    driver: local